const GITHUB_AUTH_TOKEN = "PRABATH-MD~dztkFLzI#5Zai3MIghLQSwtCisBD7V6B3kYtDc8D5iY3pOCzKhTI"
const BOT_NUMBER = "94773913394"
const SESSION_ID = "PRABATH-MD~dztkFLzI#5Zai3MIghLQSwtCisBD7V6B3kYtDc8D5iY3pOCzKhTI"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
